// Generated by Haxe 4.1.1
#ifndef INCLUDED_shoppingcart_CartModel
#define INCLUDED_shoppingcart_CartModel

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_STACK_FRAME(_hx_pos_dc2133e6e5d2b685_5_new)
HX_DECLARE_CLASS1(shoppingcart,CartModel)

namespace shoppingcart{


class HXCPP_CLASS_ATTRIBUTES CartModel_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef CartModel_obj OBJ_;
		CartModel_obj();

	public:
		enum { _hx_ClassId = 0x4cbb0cc1 };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=true,const char *inName="shoppingcart.CartModel")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,true,"shoppingcart.CartModel"); }

		inline static ::hx::ObjectPtr< CartModel_obj > __new() {
			::hx::ObjectPtr< CartModel_obj > __this = new CartModel_obj();
			__this->__construct();
			return __this;
		}

		inline static ::hx::ObjectPtr< CartModel_obj > __alloc(::hx::Ctx *_hx_ctx) {
			CartModel_obj *__this = (CartModel_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(CartModel_obj), true, "shoppingcart.CartModel"));
			*(void **)__this = CartModel_obj::_hx_vtable;
{
            	HX_STACKFRAME(&_hx_pos_dc2133e6e5d2b685_5_new)
            	}
		
			return __this;
		}

		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~CartModel_obj();

		HX_DO_RTTI_ALL;
		::hx::Val __Field(const ::String &inString, ::hx::PropertyAccess inCallProp);
		::hx::Val __SetField(const ::String &inString,const ::hx::Val &inValue, ::hx::PropertyAccess inCallProp);
		void __GetFields(Array< ::String> &outFields);
		static void __register();
		void __Mark(HX_MARK_PARAMS);
		void __Visit(HX_VISIT_PARAMS);
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("CartModel",89,09,c6,66); }

		::String id;
		::String storeId;
};

} // end namespace shoppingcart

#endif /* INCLUDED_shoppingcart_CartModel */ 
