// Generated by Haxe 4.1.1
#ifndef INCLUDED_shoppingcart_ItemModel
#define INCLUDED_shoppingcart_ItemModel

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_STACK_FRAME(_hx_pos_79353e81683b88b0_5_new)
HX_DECLARE_CLASS1(shoppingcart,ItemModel)

namespace shoppingcart{


class HXCPP_CLASS_ATTRIBUTES ItemModel_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef ItemModel_obj OBJ_;
		ItemModel_obj();

	public:
		enum { _hx_ClassId = 0x05e337ca };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=true,const char *inName="shoppingcart.ItemModel")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,true,"shoppingcart.ItemModel"); }

		inline static ::hx::ObjectPtr< ItemModel_obj > __new() {
			::hx::ObjectPtr< ItemModel_obj > __this = new ItemModel_obj();
			__this->__construct();
			return __this;
		}

		inline static ::hx::ObjectPtr< ItemModel_obj > __alloc(::hx::Ctx *_hx_ctx) {
			ItemModel_obj *__this = (ItemModel_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(ItemModel_obj), true, "shoppingcart.ItemModel"));
			*(void **)__this = ItemModel_obj::_hx_vtable;
{
            	HX_STACKFRAME(&_hx_pos_79353e81683b88b0_5_new)
            	}
		
			return __this;
		}

		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~ItemModel_obj();

		HX_DO_RTTI_ALL;
		::hx::Val __Field(const ::String &inString, ::hx::PropertyAccess inCallProp);
		::hx::Val __SetField(const ::String &inString,const ::hx::Val &inValue, ::hx::PropertyAccess inCallProp);
		void __GetFields(Array< ::String> &outFields);
		static void __register();
		void __Mark(HX_MARK_PARAMS);
		void __Visit(HX_VISIT_PARAMS);
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("ItemModel",76,69,16,ae); }

		::String cartId;
		int idx;
		::String itemId;
		int qty;
		Float price;
};

} // end namespace shoppingcart

#endif /* INCLUDED_shoppingcart_ItemModel */ 
