// Generated by Haxe 4.1.1
#ifndef INCLUDED_shoppingcart_ShoppingCart
#define INCLUDED_shoppingcart_ShoppingCart

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

#ifndef INCLUDED_16d41c6fc5b8bf5d
#define INCLUDED_16d41c6fc5b8bf5d
#include "maglev/MagLev.h"
#endif
HX_DECLARE_CLASS1(shoppingcart,ShoppingCart)
HX_DECLARE_CLASS1(shoppingcart,ShoppingCartLogic)

namespace shoppingcart{


class HXCPP_CLASS_ATTRIBUTES ShoppingCart_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef ShoppingCart_obj OBJ_;
		ShoppingCart_obj();

	public:
		enum { _hx_ClassId = 0x20575118 };

		void __construct( ::maglev::MagLev maglev);
		inline void *operator new(size_t inSize, bool inContainer=true,const char *inName="shoppingcart.ShoppingCart")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,true,"shoppingcart.ShoppingCart"); }
		static ::hx::ObjectPtr< ShoppingCart_obj > __new( ::maglev::MagLev maglev);
		static ::hx::ObjectPtr< ShoppingCart_obj > __alloc(::hx::Ctx *_hx_ctx, ::maglev::MagLev maglev);
		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~ShoppingCart_obj();

		HX_DO_RTTI_ALL;
		::hx::Val __Field(const ::String &inString, ::hx::PropertyAccess inCallProp);
		::hx::Val __SetField(const ::String &inString,const ::hx::Val &inValue, ::hx::PropertyAccess inCallProp);
		void __GetFields(Array< ::String> &outFields);
		static void __register();
		void __Mark(HX_MARK_PARAMS);
		void __Visit(HX_VISIT_PARAMS);
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("ShoppingCart",88,64,ce,df); }

		static void __boot();
		static  ::Dynamic __meta__;
		 ::maglev::MagLev maglev;
		 ::shoppingcart::ShoppingCartLogic logic;
		void registerMyMethods();
		::Dynamic registerMyMethods_dyn();

};

} // end namespace shoppingcart

#endif /* INCLUDED_shoppingcart_ShoppingCart */ 
