// Generated by Haxe 4.1.1
#ifndef INCLUDED_maglev_MagLevNull
#define INCLUDED_maglev_MagLevNull

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

#ifndef INCLUDED_maglev_MagLevAny
#include <maglev/MagLevAny.h>
#endif
HX_DECLARE_CLASS1(maglev,MagLevAny)
HX_DECLARE_CLASS1(maglev,MagLevNull)
HX_DECLARE_CLASS1(maglev,MagLevString)

namespace maglev{


class HXCPP_CLASS_ATTRIBUTES MagLevNull_obj : public  ::maglev::MagLevAny_obj
{
	public:
		typedef  ::maglev::MagLevAny_obj super;
		typedef MagLevNull_obj OBJ_;
		MagLevNull_obj();

	public:
		enum { _hx_ClassId = 0x7cdfae7b };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=false,const char *inName="maglev.MagLevNull")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,false,"maglev.MagLevNull"); }
		static ::hx::ObjectPtr< MagLevNull_obj > __new();
		static ::hx::ObjectPtr< MagLevNull_obj > __alloc(::hx::Ctx *_hx_ctx);
		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~MagLevNull_obj();

		HX_DO_RTTI_ALL;
		::hx::Val __Field(const ::String &inString, ::hx::PropertyAccess inCallProp);
		static bool __GetStatic(const ::String &inString, Dynamic &outValue, ::hx::PropertyAccess inCallProp);
		static void __register();
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("MagLevNull",d1,b2,c5,a6); }

		static  ::maglev::MagLevNull create();
		static ::Dynamic create_dyn();

		static int getStaticType();
		static ::Dynamic getStaticType_dyn();

		static  ::maglev::MagLevAny wrap( ::maglev::MagLevAny o);
		static ::Dynamic wrap_dyn();

		int getType();

		bool isEqual( ::maglev::MagLevAny other);

		 ::maglev::MagLevString toJson();

};

} // end namespace maglev

#endif /* INCLUDED_maglev_MagLevNull */ 
