// Generated by Haxe 4.1.1
#ifndef INCLUDED_maglev_MagLevArray
#define INCLUDED_maglev_MagLevArray

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

#ifndef INCLUDED_maglev_MagLevAny
#include <maglev/MagLevAny.h>
#endif
HX_DECLARE_CLASS1(maglev,MagLevAny)
HX_DECLARE_CLASS1(maglev,MagLevArray)
HX_DECLARE_CLASS1(maglev,MagLevString)

namespace maglev{


class HXCPP_CLASS_ATTRIBUTES MagLevArray_obj : public  ::maglev::MagLevAny_obj
{
	public:
		typedef  ::maglev::MagLevAny_obj super;
		typedef MagLevArray_obj OBJ_;
		MagLevArray_obj();

	public:
		enum { _hx_ClassId = 0x48ac5325 };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=true,const char *inName="maglev.MagLevArray")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,true,"maglev.MagLevArray"); }
		static ::hx::ObjectPtr< MagLevArray_obj > __new();
		static ::hx::ObjectPtr< MagLevArray_obj > __alloc(::hx::Ctx *_hx_ctx);
		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~MagLevArray_obj();

		HX_DO_RTTI_ALL;
		::hx::Val __Field(const ::String &inString, ::hx::PropertyAccess inCallProp);
		static bool __GetStatic(const ::String &inString, Dynamic &outValue, ::hx::PropertyAccess inCallProp);
		::hx::Val __SetField(const ::String &inString,const ::hx::Val &inValue, ::hx::PropertyAccess inCallProp);
		void __GetFields(Array< ::String> &outFields);
		static void __register();
		void __Mark(HX_MARK_PARAMS);
		void __Visit(HX_VISIT_PARAMS);
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("MagLevArray",0f,1a,0a,c8); }

		static  ::maglev::MagLevArray create();
		static ::Dynamic create_dyn();

		static int getStaticType();
		static ::Dynamic getStaticType_dyn();

		::Array< ::Dynamic> values;
		int size();
		::Dynamic size_dyn();

		 ::maglev::MagLevAny pop();
		::Dynamic pop_dyn();

		int push( ::maglev::MagLevAny x);
		::Dynamic push_dyn();

		 ::maglev::MagLevAny shift();
		::Dynamic shift_dyn();

		void unshift( ::maglev::MagLevAny x);
		::Dynamic unshift_dyn();

		void reverse();
		::Dynamic reverse_dyn();

		 ::maglev::MagLevAny get(int i);
		::Dynamic get_dyn();

		void set(int i, ::maglev::MagLevAny value);
		::Dynamic set_dyn();

		int getType();

		bool isEqual( ::maglev::MagLevAny other);

		 ::maglev::MagLevString toJson();

};

} // end namespace maglev

#endif /* INCLUDED_maglev_MagLevArray */ 
