// Generated by Haxe 4.1.1
#include <hxcpp.h>

#ifndef INCLUDED_16d41c6fc5b8bf5d
#define INCLUDED_16d41c6fc5b8bf5d
#include "maglev/MagLev.h"
#endif
#ifndef INCLUDED_haxe_IMap
#include <haxe/IMap.h>
#endif
#ifndef INCLUDED_haxe_ds_StringMap
#include <haxe/ds/StringMap.h>
#endif
#ifndef INCLUDED_shoppingcart_ItemModel
#include <shoppingcart/ItemModel.h>
#endif
#ifndef INCLUDED_shoppingcart_ItemRepository
#include <shoppingcart/ItemRepository.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_3617cbac9e4e1513_11_new,"shoppingcart.ItemRepository","new",0x7b95ca75,"shoppingcart.ItemRepository.new","shoppingcart/ItemRepository.hx",11,0x9b8de97a)
HX_LOCAL_STACK_FRAME(_hx_pos_3617cbac9e4e1513_16_Add,"shoppingcart.ItemRepository","Add",0x7b73a416,"shoppingcart.ItemRepository.Add","shoppingcart/ItemRepository.hx",16,0x9b8de97a)
HX_LOCAL_STACK_FRAME(_hx_pos_3617cbac9e4e1513_44_Edit,"shoppingcart.ItemRepository","Edit",0x8c60ce75,"shoppingcart.ItemRepository.Edit","shoppingcart/ItemRepository.hx",44,0x9b8de97a)
HX_LOCAL_STACK_FRAME(_hx_pos_3617cbac9e4e1513_49_Remove,"shoppingcart.ItemRepository","Remove",0xc9b4d16f,"shoppingcart.ItemRepository.Remove","shoppingcart/ItemRepository.hx",49,0x9b8de97a)
HX_LOCAL_STACK_FRAME(_hx_pos_3617cbac9e4e1513_55_FindByCartId,"shoppingcart.ItemRepository","FindByCartId",0x45c9afd6,"shoppingcart.ItemRepository.FindByCartId","shoppingcart/ItemRepository.hx",55,0x9b8de97a)
HX_LOCAL_STACK_FRAME(_hx_pos_3617cbac9e4e1513_62_FindByCartIdAndIdx,"shoppingcart.ItemRepository","FindByCartIdAndIdx",0xc73f8a1c,"shoppingcart.ItemRepository.FindByCartIdAndIdx","shoppingcart/ItemRepository.hx",62,0x9b8de97a)
namespace shoppingcart{

void ItemRepository_obj::__construct( ::maglev::MagLev bus){
            	HX_GC_STACKFRAME(&_hx_pos_3617cbac9e4e1513_11_new)
HXLINE(  12)		this->bus = bus;
HXLINE(  13)		this->items =  ::haxe::ds::StringMap_obj::__alloc( HX_CTX );
            	}

Dynamic ItemRepository_obj::__CreateEmpty() { return new ItemRepository_obj; }

void *ItemRepository_obj::_hx_vtable = 0;

Dynamic ItemRepository_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< ItemRepository_obj > _hx_result = new ItemRepository_obj();
	_hx_result->__construct(inArgs[0]);
	return _hx_result;
}

bool ItemRepository_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x61f3e465;
}

void ItemRepository_obj::Add( ::shoppingcart::ItemModel item, ::Dynamic callback){
            	HX_STACKFRAME(&_hx_pos_3617cbac9e4e1513_16_Add)
HXLINE(  17)		if (!(this->items->exists(item->cartId))) {
HXLINE(  18)			::Dynamic this1 = this->items;
HXDLIN(  18)			::String k = item->cartId;
HXDLIN(  18)			::Array< ::Dynamic> v = ::Array_obj< ::Dynamic>::__new();
HXDLIN(  18)			( ( ::haxe::ds::StringMap)(this1) )->set(k,v);
            		}
HXLINE(  20)		int idx = ( (::Array< ::Dynamic>)(this->items->get(item->cartId)) )->length;
HXLINE(  21)		item->idx = idx;
HXLINE(  22)		( (::Array< ::Dynamic>)(this->items->get(item->cartId)) )->push(item);
HXLINE(  23)		callback(idx);
            	}


HX_DEFINE_DYNAMIC_FUNC2(ItemRepository_obj,Add,(void))

void ItemRepository_obj::Edit( ::shoppingcart::ItemModel item, ::Dynamic callback){
            	HX_STACKFRAME(&_hx_pos_3617cbac9e4e1513_44_Edit)
HXLINE(  45)		this->items->get(item->cartId)->__SetItem(item->idx,item);
HXLINE(  46)		callback();
            	}


HX_DEFINE_DYNAMIC_FUNC2(ItemRepository_obj,Edit,(void))

void ItemRepository_obj::Remove(::String cartId,int idx, ::Dynamic callback){
            	HX_STACKFRAME(&_hx_pos_3617cbac9e4e1513_49_Remove)
HXLINE(  50)		this->items->get(cartId)->__SetItem(idx,null());
HXLINE(  51)		callback();
            	}


HX_DEFINE_DYNAMIC_FUNC3(ItemRepository_obj,Remove,(void))

void ItemRepository_obj::FindByCartId(::String cartId, ::Dynamic callback){
            	HX_STACKFRAME(&_hx_pos_3617cbac9e4e1513_55_FindByCartId)
HXDLIN(  55)		if (this->items->exists(cartId)) {
HXLINE(  56)			callback(this->items->get(cartId));
            		}
            		else {
HXLINE(  58)			callback(::Array_obj< ::Dynamic>::__new());
            		}
            	}


HX_DEFINE_DYNAMIC_FUNC2(ItemRepository_obj,FindByCartId,(void))

void ItemRepository_obj::FindByCartIdAndIdx(::String cartId,int idx, ::Dynamic callback){
            	HX_STACKFRAME(&_hx_pos_3617cbac9e4e1513_62_FindByCartIdAndIdx)
HXLINE(  63)		if (this->items->exists(cartId)) {
HXLINE(  64)			if ((( (::Array< ::Dynamic>)(this->items->get(cartId)) )->length > idx)) {
HXLINE(  65)				callback(Dynamic( this->items->get(cartId)->__GetItem(idx)).StaticCast<  ::shoppingcart::ItemModel >());
HXLINE(  66)				return;
            			}
            		}
HXLINE(  69)		callback(null());
            	}


HX_DEFINE_DYNAMIC_FUNC3(ItemRepository_obj,FindByCartIdAndIdx,(void))


::hx::ObjectPtr< ItemRepository_obj > ItemRepository_obj::__new( ::maglev::MagLev bus) {
	::hx::ObjectPtr< ItemRepository_obj > __this = new ItemRepository_obj();
	__this->__construct(bus);
	return __this;
}

::hx::ObjectPtr< ItemRepository_obj > ItemRepository_obj::__alloc(::hx::Ctx *_hx_ctx, ::maglev::MagLev bus) {
	ItemRepository_obj *__this = (ItemRepository_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(ItemRepository_obj), true, "shoppingcart.ItemRepository"));
	*(void **)__this = ItemRepository_obj::_hx_vtable;
	__this->__construct(bus);
	return __this;
}

ItemRepository_obj::ItemRepository_obj()
{
}

void ItemRepository_obj::__Mark(HX_MARK_PARAMS)
{
	HX_MARK_BEGIN_CLASS(ItemRepository);
	HX_MARK_MEMBER_NAME(bus,"bus");
	HX_MARK_MEMBER_NAME(items,"items");
	HX_MARK_END_CLASS();
}

void ItemRepository_obj::__Visit(HX_VISIT_PARAMS)
{
	HX_VISIT_MEMBER_NAME(bus,"bus");
	HX_VISIT_MEMBER_NAME(items,"items");
}

::hx::Val ItemRepository_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 3:
		if (HX_FIELD_EQ(inName,"bus") ) { return ::hx::Val( bus ); }
		if (HX_FIELD_EQ(inName,"Add") ) { return ::hx::Val( Add_dyn() ); }
		break;
	case 4:
		if (HX_FIELD_EQ(inName,"Edit") ) { return ::hx::Val( Edit_dyn() ); }
		break;
	case 5:
		if (HX_FIELD_EQ(inName,"items") ) { return ::hx::Val( items ); }
		break;
	case 6:
		if (HX_FIELD_EQ(inName,"Remove") ) { return ::hx::Val( Remove_dyn() ); }
		break;
	case 12:
		if (HX_FIELD_EQ(inName,"FindByCartId") ) { return ::hx::Val( FindByCartId_dyn() ); }
		break;
	case 18:
		if (HX_FIELD_EQ(inName,"FindByCartIdAndIdx") ) { return ::hx::Val( FindByCartIdAndIdx_dyn() ); }
	}
	return super::__Field(inName,inCallProp);
}

::hx::Val ItemRepository_obj::__SetField(const ::String &inName,const ::hx::Val &inValue,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 3:
		if (HX_FIELD_EQ(inName,"bus") ) { bus=inValue.Cast<  ::maglev::MagLev >(); return inValue; }
		break;
	case 5:
		if (HX_FIELD_EQ(inName,"items") ) { items=inValue.Cast<  ::haxe::ds::StringMap >(); return inValue; }
	}
	return super::__SetField(inName,inValue,inCallProp);
}

void ItemRepository_obj::__GetFields(Array< ::String> &outFields)
{
	outFields->push(HX_("bus",40,c3,4a,00));
	outFields->push(HX_("items",00,ac,0c,c2));
	super::__GetFields(outFields);
};

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo ItemRepository_obj_sMemberStorageInfo[] = {
	{::hx::fsUnknown /*  ::maglev::MagLev */ ,(int)offsetof(ItemRepository_obj,bus),HX_("bus",40,c3,4a,00)},
	{::hx::fsObject /*  ::haxe::ds::StringMap */ ,(int)offsetof(ItemRepository_obj,items),HX_("items",00,ac,0c,c2)},
	{ ::hx::fsUnknown, 0, null()}
};
static ::hx::StaticInfo *ItemRepository_obj_sStaticStorageInfo = 0;
#endif

static ::String ItemRepository_obj_sMemberFields[] = {
	HX_("bus",40,c3,4a,00),
	HX_("items",00,ac,0c,c2),
	HX_("Add",01,aa,31,00),
	HX_("Edit",2a,f6,e7,2d),
	HX_("Remove",64,10,1d,39),
	HX_("FindByCartId",8b,14,ff,31),
	HX_("FindByCartIdAndIdx",91,e4,44,12),
	::String(null()) };

::hx::Class ItemRepository_obj::__mClass;

void ItemRepository_obj::__register()
{
	ItemRepository_obj _hx_dummy;
	ItemRepository_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("shoppingcart.ItemRepository",03,6c,00,5c);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &::hx::Class_obj::GetNoStaticField;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(0 /* sStaticFields */);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(ItemRepository_obj_sMemberFields);
	__mClass->mCanCast = ::hx::TCanCast< ItemRepository_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = ItemRepository_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = ItemRepository_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace shoppingcart
