// Generated by Haxe 4.1.1
#include <hxcpp.h>

#ifndef INCLUDED_16d41c6fc5b8bf5d
#define INCLUDED_16d41c6fc5b8bf5d
#include "maglev/MagLev.h"
#endif
#ifndef INCLUDED_869a921fcf5bba54
#define INCLUDED_869a921fcf5bba54
#include "maglev/MagLevAny.h"
#endif
#ifndef INCLUDED_20db69a30a45e926
#define INCLUDED_20db69a30a45e926
#include "maglev/MagLevArray.h"
#endif
#ifndef INCLUDED_7f9204b932c8d809
#define INCLUDED_7f9204b932c8d809
#include "maglev/MagLevFunction.h"
#endif
#ifndef INCLUDED_ba46386e6aba7150
#define INCLUDED_ba46386e6aba7150
#include "maglev/MagLevNull.h"
#endif
#ifndef INCLUDED_95fa5e9194badcf5
#define INCLUDED_95fa5e9194badcf5
#include "maglev/MagLevNumber.h"
#endif
#ifndef INCLUDED_f4da16f85a617f60
#define INCLUDED_f4da16f85a617f60
#include "maglev/MagLevObject.h"
#endif
#ifndef INCLUDED_65acb6100057af6e
#define INCLUDED_65acb6100057af6e
#include "maglev/MagLevResult.h"
#endif
#ifndef INCLUDED_c859d2752ef86c43
#define INCLUDED_c859d2752ef86c43
#include "maglev/MagLevString.h"
#endif
#ifndef INCLUDED_shoppingcart_CartRepository
#include <shoppingcart/CartRepository.h>
#endif
#ifndef INCLUDED_shoppingcart_ItemRepository
#include <shoppingcart/ItemRepository.h>
#endif
#ifndef INCLUDED_shoppingcart_ShoppingCart
#include <shoppingcart/ShoppingCart.h>
#endif
#ifndef INCLUDED_shoppingcart_ShoppingCartLogic
#include <shoppingcart/ShoppingCartLogic.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_42598b115c0be80e_15_new,"shoppingcart.ShoppingCart","new",0x67096860,"shoppingcart.ShoppingCart.new","shoppingcart/ShoppingCart.hx",15,0xa535ec2f)
HX_LOCAL_STACK_FRAME(_hx_pos_42598b115c0be80e_28_registerMyMethods,"shoppingcart.ShoppingCart","registerMyMethods",0xf95a4983,"shoppingcart.ShoppingCart.registerMyMethods","shoppingcart/ShoppingCart.hx",28,0xa535ec2f)
HX_LOCAL_STACK_FRAME(_hx_pos_42598b115c0be80e_24_registerMyMethods,"shoppingcart.ShoppingCart","registerMyMethods",0xf95a4983,"shoppingcart.ShoppingCart.registerMyMethods","shoppingcart/ShoppingCart.hx",24,0xa535ec2f)
HX_LOCAL_STACK_FRAME(_hx_pos_42598b115c0be80e_39_registerMyMethods,"shoppingcart.ShoppingCart","registerMyMethods",0xf95a4983,"shoppingcart.ShoppingCart.registerMyMethods","shoppingcart/ShoppingCart.hx",39,0xa535ec2f)
HX_LOCAL_STACK_FRAME(_hx_pos_42598b115c0be80e_32_registerMyMethods,"shoppingcart.ShoppingCart","registerMyMethods",0xf95a4983,"shoppingcart.ShoppingCart.registerMyMethods","shoppingcart/ShoppingCart.hx",32,0xa535ec2f)
HX_LOCAL_STACK_FRAME(_hx_pos_42598b115c0be80e_46_registerMyMethods,"shoppingcart.ShoppingCart","registerMyMethods",0xf95a4983,"shoppingcart.ShoppingCart.registerMyMethods","shoppingcart/ShoppingCart.hx",46,0xa535ec2f)
HX_LOCAL_STACK_FRAME(_hx_pos_42598b115c0be80e_43_registerMyMethods,"shoppingcart.ShoppingCart","registerMyMethods",0xf95a4983,"shoppingcart.ShoppingCart.registerMyMethods","shoppingcart/ShoppingCart.hx",43,0xa535ec2f)
HX_LOCAL_STACK_FRAME(_hx_pos_42598b115c0be80e_65_registerMyMethods,"shoppingcart.ShoppingCart","registerMyMethods",0xf95a4983,"shoppingcart.ShoppingCart.registerMyMethods","shoppingcart/ShoppingCart.hx",65,0xa535ec2f)
HX_LOCAL_STACK_FRAME(_hx_pos_42598b115c0be80e_60_registerMyMethods,"shoppingcart.ShoppingCart","registerMyMethods",0xf95a4983,"shoppingcart.ShoppingCart.registerMyMethods","shoppingcart/ShoppingCart.hx",60,0xa535ec2f)
HX_LOCAL_STACK_FRAME(_hx_pos_42598b115c0be80e_75_registerMyMethods,"shoppingcart.ShoppingCart","registerMyMethods",0xf95a4983,"shoppingcart.ShoppingCart.registerMyMethods","shoppingcart/ShoppingCart.hx",75,0xa535ec2f)
HX_LOCAL_STACK_FRAME(_hx_pos_42598b115c0be80e_69_registerMyMethods,"shoppingcart.ShoppingCart","registerMyMethods",0xf95a4983,"shoppingcart.ShoppingCart.registerMyMethods","shoppingcart/ShoppingCart.hx",69,0xa535ec2f)
HX_LOCAL_STACK_FRAME(_hx_pos_42598b115c0be80e_83_registerMyMethods,"shoppingcart.ShoppingCart","registerMyMethods",0xf95a4983,"shoppingcart.ShoppingCart.registerMyMethods","shoppingcart/ShoppingCart.hx",83,0xa535ec2f)
HX_LOCAL_STACK_FRAME(_hx_pos_42598b115c0be80e_79_registerMyMethods,"shoppingcart.ShoppingCart","registerMyMethods",0xf95a4983,"shoppingcart.ShoppingCart.registerMyMethods","shoppingcart/ShoppingCart.hx",79,0xa535ec2f)
HX_LOCAL_STACK_FRAME(_hx_pos_42598b115c0be80e_90_registerMyMethods,"shoppingcart.ShoppingCart","registerMyMethods",0xf95a4983,"shoppingcart.ShoppingCart.registerMyMethods","shoppingcart/ShoppingCart.hx",90,0xa535ec2f)
HX_LOCAL_STACK_FRAME(_hx_pos_42598b115c0be80e_87_registerMyMethods,"shoppingcart.ShoppingCart","registerMyMethods",0xf95a4983,"shoppingcart.ShoppingCart.registerMyMethods","shoppingcart/ShoppingCart.hx",87,0xa535ec2f)
HX_LOCAL_STACK_FRAME(_hx_pos_42598b115c0be80e_102_registerMyMethods,"shoppingcart.ShoppingCart","registerMyMethods",0xf95a4983,"shoppingcart.ShoppingCart.registerMyMethods","shoppingcart/ShoppingCart.hx",102,0xa535ec2f)
HX_LOCAL_STACK_FRAME(_hx_pos_42598b115c0be80e_98_registerMyMethods,"shoppingcart.ShoppingCart","registerMyMethods",0xf95a4983,"shoppingcart.ShoppingCart.registerMyMethods","shoppingcart/ShoppingCart.hx",98,0xa535ec2f)
HX_LOCAL_STACK_FRAME(_hx_pos_42598b115c0be80e_23_registerMyMethods,"shoppingcart.ShoppingCart","registerMyMethods",0xf95a4983,"shoppingcart.ShoppingCart.registerMyMethods","shoppingcart/ShoppingCart.hx",23,0xa535ec2f)
HX_LOCAL_STACK_FRAME(_hx_pos_42598b115c0be80e_12_boot,"shoppingcart.ShoppingCart","boot",0xb94aec32,"shoppingcart.ShoppingCart.boot","shoppingcart/ShoppingCart.hx",12,0xa535ec2f)
namespace shoppingcart{

void ShoppingCart_obj::__construct( ::maglev::MagLev maglev){
            	HX_GC_STACKFRAME(&_hx_pos_42598b115c0be80e_15_new)
HXLINE(  16)		this->maglev = maglev;
HXLINE(  18)		 ::shoppingcart::CartRepository _hx_tmp =  ::shoppingcart::CartRepository_obj::__alloc( HX_CTX ,maglev);
HXLINE(  17)		this->logic =  ::shoppingcart::ShoppingCartLogic_obj::__alloc( HX_CTX ,_hx_tmp, ::shoppingcart::ItemRepository_obj::__alloc( HX_CTX ,maglev));
HXLINE(  21)		this->registerMyMethods();
            	}

Dynamic ShoppingCart_obj::__CreateEmpty() { return new ShoppingCart_obj; }

void *ShoppingCart_obj::_hx_vtable = 0;

Dynamic ShoppingCart_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< ShoppingCart_obj > _hx_result = new ShoppingCart_obj();
	_hx_result->__construct(inArgs[0]);
	return _hx_result;
}

bool ShoppingCart_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x20575118;
}

void ShoppingCart_obj::registerMyMethods(){
            		HX_BEGIN_LOCAL_FUNC_S1(::hx::LocalFunc,_hx_Closure_1, ::shoppingcart::ShoppingCart,_gthis) HXARGC(1)
            		 ::maglev::MagLevResult _hx_run( ::maglev::MagLevArray args){
            			HX_BEGIN_LOCAL_FUNC_S1(::hx::LocalFunc,_hx_Closure_0, ::maglev::MagLevResult,result) HXARGC(1)
            			void _hx_run(::String cartId){
            				HX_STACKFRAME(&_hx_pos_42598b115c0be80e_28_registerMyMethods)
HXLINE(  28)				 ::maglev::MagLevResult result1 = result;
HXDLIN(  28)				result1->setResult(::maglev::MagLevString_obj::fromString(cartId));
            			}
            			HX_END_LOCAL_FUNC1((void))

            			HX_STACKFRAME(&_hx_pos_42598b115c0be80e_24_registerMyMethods)
HXLINE(  25)			::String storeId = ::hx::TCast<  ::maglev::MagLevString >::cast(args->get(0))->getString();
HXLINE(  26)			 ::maglev::MagLevResult result = ::maglev::MagLevResult_obj::createAsync();
HXLINE(  27)			_gthis->logic->Create(storeId, ::Dynamic(new _hx_Closure_0(result)));
HXLINE(  30)			return result;
            		}
            		HX_END_LOCAL_FUNC1(return)

            		HX_BEGIN_LOCAL_FUNC_S1(::hx::LocalFunc,_hx_Closure_3, ::shoppingcart::ShoppingCart,_gthis) HXARGC(1)
            		 ::maglev::MagLevResult _hx_run( ::maglev::MagLevArray args){
            			HX_BEGIN_LOCAL_FUNC_S1(::hx::LocalFunc,_hx_Closure_2, ::maglev::MagLevResult,result) HXARGC(1)
            			void _hx_run(int idx){
            				HX_STACKFRAME(&_hx_pos_42598b115c0be80e_39_registerMyMethods)
HXLINE(  39)				 ::maglev::MagLevResult result1 = result;
HXDLIN(  39)				result1->setResult(::maglev::MagLevNumber_obj::fromInt(idx));
            			}
            			HX_END_LOCAL_FUNC1((void))

            			HX_STACKFRAME(&_hx_pos_42598b115c0be80e_32_registerMyMethods)
HXLINE(  33)			::String cartId = ::hx::TCast<  ::maglev::MagLevString >::cast(args->get(0))->getString();
HXLINE(  34)			::String itemId = ::hx::TCast<  ::maglev::MagLevString >::cast(args->get(1))->getString();
HXLINE(  35)			int qty = ::hx::TCast<  ::maglev::MagLevNumber >::cast(args->get(2))->getInt();
HXLINE(  36)			Float price = ::hx::TCast<  ::maglev::MagLevNumber >::cast(args->get(3))->getFloat();
HXLINE(  37)			 ::maglev::MagLevResult result = ::maglev::MagLevResult_obj::createAsync();
HXLINE(  38)			_gthis->logic->AddItem(cartId,itemId,qty,price, ::Dynamic(new _hx_Closure_2(result)));
HXLINE(  41)			return result;
            		}
            		HX_END_LOCAL_FUNC1(return)

            		HX_BEGIN_LOCAL_FUNC_S1(::hx::LocalFunc,_hx_Closure_5, ::shoppingcart::ShoppingCart,_gthis) HXARGC(1)
            		 ::maglev::MagLevResult _hx_run( ::maglev::MagLevArray args){
            			HX_BEGIN_LOCAL_FUNC_S1(::hx::LocalFunc,_hx_Closure_4, ::maglev::MagLevResult,result) HXARGC(1)
            			void _hx_run(::Array< ::Dynamic> items){
            				HX_STACKFRAME(&_hx_pos_42598b115c0be80e_46_registerMyMethods)
HXLINE(  47)				 ::maglev::MagLevArray arr = ::maglev::MagLevArray_obj::create();
HXLINE(  48)				{
HXLINE(  48)					int _g = 0;
HXDLIN(  48)					while((_g < items->length)){
HXLINE(  48)						 ::Dynamic item = items->__get(_g);
HXDLIN(  48)						_g = (_g + 1);
HXLINE(  49)						 ::maglev::MagLevObject obj = ::maglev::MagLevObject_obj::create();
HXLINE(  50)						obj->set(HX_("idx",3d,04,50,00),::maglev::MagLevNumber_obj::fromInt(( (int)(item->__Field(HX_("idx",3d,04,50,00),::hx::paccDynamic)) )));
HXLINE(  51)						obj->set(HX_("itemId",ce,af,09,09),::maglev::MagLevString_obj::fromString(( (::String)(item->__Field(HX_("itemId",ce,af,09,09),::hx::paccDynamic)) )));
HXLINE(  52)						obj->set(HX_("qty",36,24,56,00),::maglev::MagLevNumber_obj::fromFloat(( (Float)(item->__Field(HX_("qty",36,24,56,00),::hx::paccDynamic)) )));
HXLINE(  53)						obj->set(HX_("price",89,4e,8b,c8),::maglev::MagLevNumber_obj::fromFloat(( (Float)(item->__Field(HX_("price",89,4e,8b,c8),::hx::paccDynamic)) )));
HXLINE(  54)						arr->push(obj);
            					}
            				}
HXLINE(  56)				result->setResult(arr);
            			}
            			HX_END_LOCAL_FUNC1((void))

            			HX_STACKFRAME(&_hx_pos_42598b115c0be80e_43_registerMyMethods)
HXLINE(  44)			::String cartId = ::hx::TCast<  ::maglev::MagLevString >::cast(args->get(0))->getString();
HXLINE(  45)			 ::maglev::MagLevResult result = ::maglev::MagLevResult_obj::createAsync();
HXLINE(  46)			_gthis->logic->ListItems(cartId, ::Dynamic(new _hx_Closure_4(result)));
HXLINE(  58)			return result;
            		}
            		HX_END_LOCAL_FUNC1(return)

            		HX_BEGIN_LOCAL_FUNC_S1(::hx::LocalFunc,_hx_Closure_7, ::shoppingcart::ShoppingCart,_gthis) HXARGC(1)
            		 ::maglev::MagLevResult _hx_run( ::maglev::MagLevArray args){
            			HX_BEGIN_LOCAL_FUNC_S1(::hx::LocalFunc,_hx_Closure_6, ::maglev::MagLevResult,result) HXARGC(0)
            			void _hx_run(){
            				HX_STACKFRAME(&_hx_pos_42598b115c0be80e_65_registerMyMethods)
HXLINE(  65)				 ::maglev::MagLevResult result1 = result;
HXDLIN(  65)				result1->setResult(::maglev::MagLevNull_obj::create());
            			}
            			HX_END_LOCAL_FUNC0((void))

            			HX_STACKFRAME(&_hx_pos_42598b115c0be80e_60_registerMyMethods)
HXLINE(  61)			::String cartId = ::hx::TCast<  ::maglev::MagLevString >::cast(args->get(0))->getString();
HXLINE(  62)			int idx = ::hx::TCast<  ::maglev::MagLevNumber >::cast(args->get(1))->getInt();
HXLINE(  63)			 ::maglev::MagLevResult result = ::maglev::MagLevResult_obj::createAsync();
HXLINE(  64)			_gthis->logic->RemoveItem(cartId,idx, ::Dynamic(new _hx_Closure_6(result)));
HXLINE(  67)			return result;
            		}
            		HX_END_LOCAL_FUNC1(return)

            		HX_BEGIN_LOCAL_FUNC_S1(::hx::LocalFunc,_hx_Closure_9, ::shoppingcart::ShoppingCart,_gthis) HXARGC(1)
            		 ::maglev::MagLevResult _hx_run( ::maglev::MagLevArray args){
            			HX_BEGIN_LOCAL_FUNC_S1(::hx::LocalFunc,_hx_Closure_8, ::maglev::MagLevResult,result) HXARGC(0)
            			void _hx_run(){
            				HX_STACKFRAME(&_hx_pos_42598b115c0be80e_75_registerMyMethods)
HXLINE(  75)				 ::maglev::MagLevResult result1 = result;
HXDLIN(  75)				result1->setResult(::maglev::MagLevNull_obj::create());
            			}
            			HX_END_LOCAL_FUNC0((void))

            			HX_STACKFRAME(&_hx_pos_42598b115c0be80e_69_registerMyMethods)
HXLINE(  70)			::String cartId = ::hx::TCast<  ::maglev::MagLevString >::cast(args->get(0))->getString();
HXLINE(  71)			int idx = ::hx::TCast<  ::maglev::MagLevNumber >::cast(args->get(1))->getInt();
HXLINE(  72)			int qty = ::hx::TCast<  ::maglev::MagLevNumber >::cast(args->get(2))->getInt();
HXLINE(  73)			 ::maglev::MagLevResult result = ::maglev::MagLevResult_obj::createAsync();
HXLINE(  74)			_gthis->logic->UpdateQty(cartId,idx,qty, ::Dynamic(new _hx_Closure_8(result)));
HXLINE(  77)			return result;
            		}
            		HX_END_LOCAL_FUNC1(return)

            		HX_BEGIN_LOCAL_FUNC_S1(::hx::LocalFunc,_hx_Closure_11, ::shoppingcart::ShoppingCart,_gthis) HXARGC(1)
            		 ::maglev::MagLevResult _hx_run( ::maglev::MagLevArray args){
            			HX_BEGIN_LOCAL_FUNC_S1(::hx::LocalFunc,_hx_Closure_10, ::maglev::MagLevResult,result) HXARGC(1)
            			void _hx_run(int count){
            				HX_STACKFRAME(&_hx_pos_42598b115c0be80e_83_registerMyMethods)
HXLINE(  83)				 ::maglev::MagLevResult result1 = result;
HXDLIN(  83)				result1->setResult(::maglev::MagLevNull_obj::create());
            			}
            			HX_END_LOCAL_FUNC1((void))

            			HX_STACKFRAME(&_hx_pos_42598b115c0be80e_79_registerMyMethods)
HXLINE(  80)			::String cartId = ::hx::TCast<  ::maglev::MagLevString >::cast(args->get(0))->getString();
HXLINE(  81)			 ::maglev::MagLevResult result = ::maglev::MagLevResult_obj::createAsync();
HXLINE(  82)			_gthis->logic->CountItems(cartId, ::Dynamic(new _hx_Closure_10(result)));
HXLINE(  85)			return result;
            		}
            		HX_END_LOCAL_FUNC1(return)

            		HX_BEGIN_LOCAL_FUNC_S1(::hx::LocalFunc,_hx_Closure_13, ::shoppingcart::ShoppingCart,_gthis) HXARGC(1)
            		 ::maglev::MagLevResult _hx_run( ::maglev::MagLevArray args){
            			HX_BEGIN_LOCAL_FUNC_S1(::hx::LocalFunc,_hx_Closure_12, ::maglev::MagLevResult,result) HXARGC(1)
            			void _hx_run( ::Dynamic summary){
            				HX_STACKFRAME(&_hx_pos_42598b115c0be80e_90_registerMyMethods)
HXLINE(  91)				 ::maglev::MagLevObject obj = ::maglev::MagLevObject_obj::create();
HXLINE(  92)				obj->set(HX_("items",00,ac,0c,c2),::maglev::MagLevNumber_obj::fromInt(( (int)(summary->__Field(HX_("items",00,ac,0c,c2),::hx::paccDynamic)) )));
HXLINE(  93)				obj->set(HX_("total",c4,53,32,14),::maglev::MagLevNumber_obj::fromFloat(( (Float)(summary->__Field(HX_("total",c4,53,32,14),::hx::paccDynamic)) )));
HXLINE(  94)				result->setResult(obj);
            			}
            			HX_END_LOCAL_FUNC1((void))

            			HX_STACKFRAME(&_hx_pos_42598b115c0be80e_87_registerMyMethods)
HXLINE(  88)			::String cartId = ::hx::TCast<  ::maglev::MagLevString >::cast(args->get(0))->getString();
HXLINE(  89)			 ::maglev::MagLevResult result = ::maglev::MagLevResult_obj::createAsync();
HXLINE(  90)			_gthis->logic->GetCartSummary(cartId, ::Dynamic(new _hx_Closure_12(result)));
HXLINE(  96)			return result;
            		}
            		HX_END_LOCAL_FUNC1(return)

            		HX_BEGIN_LOCAL_FUNC_S1(::hx::LocalFunc,_hx_Closure_15, ::shoppingcart::ShoppingCart,_gthis) HXARGC(1)
            		 ::maglev::MagLevResult _hx_run( ::maglev::MagLevArray args){
            			HX_BEGIN_LOCAL_FUNC_S1(::hx::LocalFunc,_hx_Closure_14, ::maglev::MagLevResult,result) HXARGC(0)
            			void _hx_run(){
            				HX_STACKFRAME(&_hx_pos_42598b115c0be80e_102_registerMyMethods)
HXLINE( 102)				 ::maglev::MagLevResult result1 = result;
HXDLIN( 102)				result1->setResult(::maglev::MagLevNull_obj::create());
            			}
            			HX_END_LOCAL_FUNC0((void))

            			HX_STACKFRAME(&_hx_pos_42598b115c0be80e_98_registerMyMethods)
HXLINE(  99)			 ::maglev::MagLevResult result = ::maglev::MagLevResult_obj::createAsync();
HXLINE( 100)			::String cartId = ::hx::TCast<  ::maglev::MagLevString >::cast(args->get(0))->getString();
HXLINE( 101)			_gthis->logic->Clear(cartId, ::Dynamic(new _hx_Closure_14(result)));
HXLINE( 104)			return result;
            		}
            		HX_END_LOCAL_FUNC1(return)

            	HX_STACKFRAME(&_hx_pos_42598b115c0be80e_23_registerMyMethods)
HXDLIN(  23)		 ::shoppingcart::ShoppingCart _gthis = ::hx::ObjectPtr<OBJ_>(this);
HXLINE(  24)		 ::maglev::MagLev _hx_tmp = this->maglev;
HXDLIN(  24)		_hx_tmp->_hx_register(HX_("ShoppingCart.Create",42,ee,d1,16),::maglev::MagLevFunction_obj::fromFunction( ::Dynamic(new _hx_Closure_1(_gthis))));
HXLINE(  32)		 ::maglev::MagLev _hx_tmp1 = this->maglev;
HXDLIN(  32)		_hx_tmp1->_hx_register(HX_("ShoppingCart.AddItem",ce,dd,70,51),::maglev::MagLevFunction_obj::fromFunction( ::Dynamic(new _hx_Closure_3(_gthis))));
HXLINE(  43)		 ::maglev::MagLev _hx_tmp2 = this->maglev;
HXDLIN(  43)		_hx_tmp2->_hx_register(HX_("ShoppingCart.ListItems",3c,33,de,4c),::maglev::MagLevFunction_obj::fromFunction( ::Dynamic(new _hx_Closure_5(_gthis))));
HXLINE(  60)		 ::maglev::MagLev _hx_tmp3 = this->maglev;
HXDLIN(  60)		_hx_tmp3->_hx_register(HX_("ShoppingCart.RemoveItem",bd,a1,fd,4c),::maglev::MagLevFunction_obj::fromFunction( ::Dynamic(new _hx_Closure_7(_gthis))));
HXLINE(  69)		 ::maglev::MagLev _hx_tmp4 = this->maglev;
HXDLIN(  69)		_hx_tmp4->_hx_register(HX_("ShoppingCart.UpdateQty",27,ca,73,f7),::maglev::MagLevFunction_obj::fromFunction( ::Dynamic(new _hx_Closure_9(_gthis))));
HXLINE(  79)		 ::maglev::MagLev _hx_tmp5 = this->maglev;
HXDLIN(  79)		_hx_tmp5->_hx_register(HX_("ShoppingCart.CountItems",f7,aa,7e,16),::maglev::MagLevFunction_obj::fromFunction( ::Dynamic(new _hx_Closure_11(_gthis))));
HXLINE(  87)		 ::maglev::MagLev _hx_tmp6 = this->maglev;
HXDLIN(  87)		_hx_tmp6->_hx_register(HX_("ShoppingCart.GetCartSummary",76,21,94,8b),::maglev::MagLevFunction_obj::fromFunction( ::Dynamic(new _hx_Closure_13(_gthis))));
HXLINE(  98)		 ::maglev::MagLev _hx_tmp7 = this->maglev;
HXDLIN(  98)		_hx_tmp7->_hx_register(HX_("ShoppingCart.Clear",07,f5,0b,68),::maglev::MagLevFunction_obj::fromFunction( ::Dynamic(new _hx_Closure_15(_gthis))));
            	}


HX_DEFINE_DYNAMIC_FUNC0(ShoppingCart_obj,registerMyMethods,(void))


::hx::ObjectPtr< ShoppingCart_obj > ShoppingCart_obj::__new( ::maglev::MagLev maglev) {
	::hx::ObjectPtr< ShoppingCart_obj > __this = new ShoppingCart_obj();
	__this->__construct(maglev);
	return __this;
}

::hx::ObjectPtr< ShoppingCart_obj > ShoppingCart_obj::__alloc(::hx::Ctx *_hx_ctx, ::maglev::MagLev maglev) {
	ShoppingCart_obj *__this = (ShoppingCart_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(ShoppingCart_obj), true, "shoppingcart.ShoppingCart"));
	*(void **)__this = ShoppingCart_obj::_hx_vtable;
	__this->__construct(maglev);
	return __this;
}

ShoppingCart_obj::ShoppingCart_obj()
{
}

void ShoppingCart_obj::__Mark(HX_MARK_PARAMS)
{
	HX_MARK_BEGIN_CLASS(ShoppingCart);
	HX_MARK_MEMBER_NAME(maglev,"maglev");
	HX_MARK_MEMBER_NAME(logic,"logic");
	HX_MARK_END_CLASS();
}

void ShoppingCart_obj::__Visit(HX_VISIT_PARAMS)
{
	HX_VISIT_MEMBER_NAME(maglev,"maglev");
	HX_VISIT_MEMBER_NAME(logic,"logic");
}

::hx::Val ShoppingCart_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 5:
		if (HX_FIELD_EQ(inName,"logic") ) { return ::hx::Val( logic ); }
		break;
	case 6:
		if (HX_FIELD_EQ(inName,"maglev") ) { return ::hx::Val( maglev ); }
		break;
	case 17:
		if (HX_FIELD_EQ(inName,"registerMyMethods") ) { return ::hx::Val( registerMyMethods_dyn() ); }
	}
	return super::__Field(inName,inCallProp);
}

::hx::Val ShoppingCart_obj::__SetField(const ::String &inName,const ::hx::Val &inValue,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 5:
		if (HX_FIELD_EQ(inName,"logic") ) { logic=inValue.Cast<  ::shoppingcart::ShoppingCartLogic >(); return inValue; }
		break;
	case 6:
		if (HX_FIELD_EQ(inName,"maglev") ) { maglev=inValue.Cast<  ::maglev::MagLev >(); return inValue; }
	}
	return super::__SetField(inName,inValue,inCallProp);
}

void ShoppingCart_obj::__GetFields(Array< ::String> &outFields)
{
	outFields->push(HX_("maglev",2a,df,2b,b3));
	outFields->push(HX_("logic",5e,d9,f3,78));
	super::__GetFields(outFields);
};

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo ShoppingCart_obj_sMemberStorageInfo[] = {
	{::hx::fsUnknown /*  ::maglev::MagLev */ ,(int)offsetof(ShoppingCart_obj,maglev),HX_("maglev",2a,df,2b,b3)},
	{::hx::fsObject /*  ::shoppingcart::ShoppingCartLogic */ ,(int)offsetof(ShoppingCart_obj,logic),HX_("logic",5e,d9,f3,78)},
	{ ::hx::fsUnknown, 0, null()}
};
static ::hx::StaticInfo *ShoppingCart_obj_sStaticStorageInfo = 0;
#endif

static ::String ShoppingCart_obj_sMemberFields[] = {
	HX_("maglev",2a,df,2b,b3),
	HX_("logic",5e,d9,f3,78),
	HX_("registerMyMethods",83,b1,0a,b9),
	::String(null()) };

::hx::Class ShoppingCart_obj::__mClass;

void ShoppingCart_obj::__register()
{
	ShoppingCart_obj _hx_dummy;
	ShoppingCart_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("shoppingcart.ShoppingCart",6e,f8,dd,df);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &::hx::Class_obj::GetNoStaticField;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(0 /* sStaticFields */);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(ShoppingCart_obj_sMemberFields);
	__mClass->mCanCast = ::hx::TCanCast< ShoppingCart_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = ShoppingCart_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = ShoppingCart_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

void ShoppingCart_obj::__boot()
{
{
            	HX_STACKFRAME(&_hx_pos_42598b115c0be80e_12_boot)
HXDLIN(  12)		__mClass->__meta__ =  ::Dynamic(::hx::Anon_obj::Create(1)
            			->setFixed(0,HX_("obj",f7,8f,54,00), ::Dynamic(::hx::Anon_obj::Create(1)
            				->setFixed(0,HX_("SuppressWarnings",0c,d3,d2,00),::cpp::VirtualArray_obj::__new(1)->init(0,::cpp::VirtualArray_obj::__new(4)->init(0,HX_("checkstyle:FieldDocComment",70,56,1b,20))->init(1,HX_("checkstyle:LocalVariableName",c1,ac,a3,03))->init(2,HX_("checkstyle:MultipleStringLiterals",d6,ed,13,79))->init(3,HX_("checkstyle:MagicNumber",a5,aa,f4,8b)))))));
            	}
}

} // end namespace shoppingcart
