// Generated by Haxe 4.1.1
#include <hxcpp.h>

#ifndef INCLUDED_shoppingcart_CartModel
#include <shoppingcart/CartModel.h>
#endif
#ifndef INCLUDED_shoppingcart_CartRepository
#include <shoppingcart/CartRepository.h>
#endif
#ifndef INCLUDED_shoppingcart_ItemModel
#include <shoppingcart/ItemModel.h>
#endif
#ifndef INCLUDED_shoppingcart_ItemRepository
#include <shoppingcart/ItemRepository.h>
#endif
#ifndef INCLUDED_shoppingcart_ShoppingCartLogic
#include <shoppingcart/ShoppingCartLogic.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_b09c8a736b8e9c2d_6_new,"shoppingcart.ShoppingCartLogic","new",0xc32feb02,"shoppingcart.ShoppingCartLogic.new","shoppingcart/ShoppingCartLogic.hx",6,0x202d512f)
HX_LOCAL_STACK_FRAME(_hx_pos_b09c8a736b8e9c2d_15_Create,"shoppingcart.ShoppingCartLogic","Create",0xb9e891ba,"shoppingcart.ShoppingCartLogic.Create","shoppingcart/ShoppingCartLogic.hx",15,0x202d512f)
HX_LOCAL_STACK_FRAME(_hx_pos_b09c8a736b8e9c2d_11_Create,"shoppingcart.ShoppingCartLogic","Create",0xb9e891ba,"shoppingcart.ShoppingCartLogic.Create","shoppingcart/ShoppingCartLogic.hx",11,0x202d512f)
HX_LOCAL_STACK_FRAME(_hx_pos_b09c8a736b8e9c2d_25_AddItem,"shoppingcart.ShoppingCartLogic","AddItem",0x62294356,"shoppingcart.ShoppingCartLogic.AddItem","shoppingcart/ShoppingCartLogic.hx",25,0x202d512f)
HX_LOCAL_STACK_FRAME(_hx_pos_b09c8a736b8e9c2d_18_AddItem,"shoppingcart.ShoppingCartLogic","AddItem",0x62294356,"shoppingcart.ShoppingCartLogic.AddItem","shoppingcart/ShoppingCartLogic.hx",18,0x202d512f)
HX_LOCAL_STACK_FRAME(_hx_pos_b09c8a736b8e9c2d_29_ListItems,"shoppingcart.ShoppingCartLogic","ListItems",0x48a10ac4,"shoppingcart.ShoppingCartLogic.ListItems","shoppingcart/ShoppingCartLogic.hx",29,0x202d512f)
HX_LOCAL_STACK_FRAME(_hx_pos_b09c8a736b8e9c2d_45_RemoveItem,"shoppingcart.ShoppingCartLogic","RemoveItem",0x9bb76135,"shoppingcart.ShoppingCartLogic.RemoveItem","shoppingcart/ShoppingCartLogic.hx",45,0x202d512f)
HX_LOCAL_STACK_FRAME(_hx_pos_b09c8a736b8e9c2d_44_RemoveItem,"shoppingcart.ShoppingCartLogic","RemoveItem",0x9bb76135,"shoppingcart.ShoppingCartLogic.RemoveItem","shoppingcart/ShoppingCartLogic.hx",44,0x202d512f)
HX_LOCAL_STACK_FRAME(_hx_pos_b09c8a736b8e9c2d_52_UpdateQty,"shoppingcart.ShoppingCartLogic","UpdateQty",0xf336a1af,"shoppingcart.ShoppingCartLogic.UpdateQty","shoppingcart/ShoppingCartLogic.hx",52,0x202d512f)
HX_LOCAL_STACK_FRAME(_hx_pos_b09c8a736b8e9c2d_49_UpdateQty,"shoppingcart.ShoppingCartLogic","UpdateQty",0xf336a1af,"shoppingcart.ShoppingCartLogic.UpdateQty","shoppingcart/ShoppingCartLogic.hx",49,0x202d512f)
HX_LOCAL_STACK_FRAME(_hx_pos_b09c8a736b8e9c2d_48_UpdateQty,"shoppingcart.ShoppingCartLogic","UpdateQty",0xf336a1af,"shoppingcart.ShoppingCartLogic.UpdateQty","shoppingcart/ShoppingCartLogic.hx",48,0x202d512f)
HX_LOCAL_STACK_FRAME(_hx_pos_b09c8a736b8e9c2d_57_CountItems,"shoppingcart.ShoppingCartLogic","CountItems",0x65386a6f,"shoppingcart.ShoppingCartLogic.CountItems","shoppingcart/ShoppingCartLogic.hx",57,0x202d512f)
HX_LOCAL_STACK_FRAME(_hx_pos_b09c8a736b8e9c2d_63_GetCartSummary,"shoppingcart.ShoppingCartLogic","GetCartSummary",0xcbaefcee,"shoppingcart.ShoppingCartLogic.GetCartSummary","shoppingcart/ShoppingCartLogic.hx",63,0x202d512f)
HX_LOCAL_STACK_FRAME(_hx_pos_b09c8a736b8e9c2d_81_Clear,"shoppingcart.ShoppingCartLogic","Clear",0x219a688f,"shoppingcart.ShoppingCartLogic.Clear","shoppingcart/ShoppingCartLogic.hx",81,0x202d512f)
HX_LOCAL_STACK_FRAME(_hx_pos_b09c8a736b8e9c2d_80_Clear,"shoppingcart.ShoppingCartLogic","Clear",0x219a688f,"shoppingcart.ShoppingCartLogic.Clear","shoppingcart/ShoppingCartLogic.hx",80,0x202d512f)
namespace shoppingcart{

void ShoppingCartLogic_obj::__construct( ::shoppingcart::CartRepository cartRepo, ::shoppingcart::ItemRepository itemRepo){
            	HX_STACKFRAME(&_hx_pos_b09c8a736b8e9c2d_6_new)
HXLINE(   7)		this->cartRepo = cartRepo;
HXLINE(   8)		this->itemRepo = itemRepo;
            	}

Dynamic ShoppingCartLogic_obj::__CreateEmpty() { return new ShoppingCartLogic_obj; }

void *ShoppingCartLogic_obj::_hx_vtable = 0;

Dynamic ShoppingCartLogic_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< ShoppingCartLogic_obj > _hx_result = new ShoppingCartLogic_obj();
	_hx_result->__construct(inArgs[0],inArgs[1]);
	return _hx_result;
}

bool ShoppingCartLogic_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x14398f5e;
}

void ShoppingCartLogic_obj::Create(::String storeId, ::Dynamic callback){
            		HX_BEGIN_LOCAL_FUNC_S1(::hx::LocalFunc,_hx_Closure_0, ::Dynamic,callback) HXARGC(1)
            		void _hx_run(::String cartId){
            			HX_GC_STACKFRAME(&_hx_pos_b09c8a736b8e9c2d_15_Create)
HXLINE(  15)			callback(cartId);
            		}
            		HX_END_LOCAL_FUNC1((void))

            	HX_GC_STACKFRAME(&_hx_pos_b09c8a736b8e9c2d_11_Create)
HXLINE(  12)		 ::shoppingcart::CartModel cart =  ::shoppingcart::CartModel_obj::__alloc( HX_CTX );
HXLINE(  13)		cart->storeId = storeId;
HXLINE(  14)		this->cartRepo->Add(cart, ::Dynamic(new _hx_Closure_0(callback)));
            	}


HX_DEFINE_DYNAMIC_FUNC2(ShoppingCartLogic_obj,Create,(void))

void ShoppingCartLogic_obj::AddItem(::String cartId,::String itemId,int qty,Float price, ::Dynamic callback){
            		HX_BEGIN_LOCAL_FUNC_S1(::hx::LocalFunc,_hx_Closure_0, ::Dynamic,callback) HXARGC(1)
            		void _hx_run(int idx){
            			HX_GC_STACKFRAME(&_hx_pos_b09c8a736b8e9c2d_25_AddItem)
HXLINE(  25)			callback(idx);
            		}
            		HX_END_LOCAL_FUNC1((void))

            	HX_GC_STACKFRAME(&_hx_pos_b09c8a736b8e9c2d_18_AddItem)
HXLINE(  19)		 ::shoppingcart::ItemModel item =  ::shoppingcart::ItemModel_obj::__alloc( HX_CTX );
HXLINE(  20)		item->cartId = cartId;
HXLINE(  21)		item->itemId = itemId;
HXLINE(  22)		item->qty = qty;
HXLINE(  23)		item->price = price;
HXLINE(  24)		this->itemRepo->Add(item, ::Dynamic(new _hx_Closure_0(callback)));
            	}


HX_DEFINE_DYNAMIC_FUNC5(ShoppingCartLogic_obj,AddItem,(void))

void ShoppingCartLogic_obj::ListItems(::String cartId, ::Dynamic callback){
            		HX_BEGIN_LOCAL_FUNC_S1(::hx::LocalFunc,_hx_Closure_0, ::Dynamic,callback) HXARGC(1)
            		void _hx_run(::Array< ::Dynamic> items){
            			HX_STACKFRAME(&_hx_pos_b09c8a736b8e9c2d_29_ListItems)
HXLINE(  30)			::Array< ::Dynamic> list = ::Array_obj< ::Dynamic>::__new();
HXLINE(  31)			{
HXLINE(  31)				int _g = 0;
HXDLIN(  31)				while((_g < items->length)){
HXLINE(  31)					 ::shoppingcart::ItemModel item = items->__get(_g).StaticCast<  ::shoppingcart::ItemModel >();
HXDLIN(  31)					_g = (_g + 1);
HXLINE(  32)					 ::Dynamic cartItem =  ::Dynamic(::hx::Anon_obj::Create(4)
            						->setFixed(0,HX_("price",89,4e,8b,c8),item->price)
            						->setFixed(1,HX_("idx",3d,04,50,00),item->idx)
            						->setFixed(2,HX_("qty",36,24,56,00),( (Float)(item->qty) ))
            						->setFixed(3,HX_("itemId",ce,af,09,09),item->itemId));
HXLINE(  38)					list->push(cartItem);
            				}
            			}
HXLINE(  40)			callback(list);
            		}
            		HX_END_LOCAL_FUNC1((void))

            	HX_STACKFRAME(&_hx_pos_b09c8a736b8e9c2d_29_ListItems)
HXDLIN(  29)		this->itemRepo->FindByCartId(cartId, ::Dynamic(new _hx_Closure_0(callback)));
            	}


HX_DEFINE_DYNAMIC_FUNC2(ShoppingCartLogic_obj,ListItems,(void))

void ShoppingCartLogic_obj::RemoveItem(::String cartId,int idx, ::Dynamic callback){
            		HX_BEGIN_LOCAL_FUNC_S1(::hx::LocalFunc,_hx_Closure_0, ::Dynamic,callback) HXARGC(0)
            		void _hx_run(){
            			HX_STACKFRAME(&_hx_pos_b09c8a736b8e9c2d_45_RemoveItem)
HXLINE(  45)			callback();
            		}
            		HX_END_LOCAL_FUNC0((void))

            	HX_STACKFRAME(&_hx_pos_b09c8a736b8e9c2d_44_RemoveItem)
HXDLIN(  44)		this->itemRepo->Remove(cartId,idx, ::Dynamic(new _hx_Closure_0(callback)));
            	}


HX_DEFINE_DYNAMIC_FUNC3(ShoppingCartLogic_obj,RemoveItem,(void))

void ShoppingCartLogic_obj::UpdateQty(::String cartId,int idx,int qty, ::Dynamic callback){
            		HX_BEGIN_LOCAL_FUNC_S3(::hx::LocalFunc,_hx_Closure_1, ::shoppingcart::ShoppingCartLogic,_gthis,int,qty, ::Dynamic,callback) HXARGC(1)
            		void _hx_run( ::shoppingcart::ItemModel item){
            			HX_BEGIN_LOCAL_FUNC_S1(::hx::LocalFunc,_hx_Closure_0, ::Dynamic,callback) HXARGC(0)
            			void _hx_run(){
            				HX_STACKFRAME(&_hx_pos_b09c8a736b8e9c2d_52_UpdateQty)
HXLINE(  52)				callback();
            			}
            			HX_END_LOCAL_FUNC0((void))

            			HX_STACKFRAME(&_hx_pos_b09c8a736b8e9c2d_49_UpdateQty)
HXLINE(  50)			item->qty = qty;
HXLINE(  51)			_gthis->itemRepo->Edit(item, ::Dynamic(new _hx_Closure_0(callback)));
            		}
            		HX_END_LOCAL_FUNC1((void))

            	HX_STACKFRAME(&_hx_pos_b09c8a736b8e9c2d_48_UpdateQty)
HXDLIN(  48)		 ::shoppingcart::ShoppingCartLogic _gthis = ::hx::ObjectPtr<OBJ_>(this);
HXLINE(  49)		this->itemRepo->FindByCartIdAndIdx(cartId,idx, ::Dynamic(new _hx_Closure_1(_gthis,qty,callback)));
            	}


HX_DEFINE_DYNAMIC_FUNC4(ShoppingCartLogic_obj,UpdateQty,(void))

void ShoppingCartLogic_obj::CountItems(::String cartId, ::Dynamic callback){
            		HX_BEGIN_LOCAL_FUNC_S1(::hx::LocalFunc,_hx_Closure_0, ::Dynamic,callback) HXARGC(1)
            		void _hx_run(::Array< ::Dynamic> items){
            			HX_STACKFRAME(&_hx_pos_b09c8a736b8e9c2d_57_CountItems)
HXLINE(  58)			int count = items->length;
HXLINE(  59)			callback(count);
            		}
            		HX_END_LOCAL_FUNC1((void))

            	HX_STACKFRAME(&_hx_pos_b09c8a736b8e9c2d_57_CountItems)
HXDLIN(  57)		this->itemRepo->FindByCartId(cartId, ::Dynamic(new _hx_Closure_0(callback)));
            	}


HX_DEFINE_DYNAMIC_FUNC2(ShoppingCartLogic_obj,CountItems,(void))

void ShoppingCartLogic_obj::GetCartSummary(::String cartId, ::Dynamic callback){
            		HX_BEGIN_LOCAL_FUNC_S1(::hx::LocalFunc,_hx_Closure_0, ::Dynamic,callback) HXARGC(1)
            		void _hx_run(::Array< ::Dynamic> items){
            			HX_STACKFRAME(&_hx_pos_b09c8a736b8e9c2d_63_GetCartSummary)
HXLINE(  64)			Float total = ( (Float)(0) );
HXLINE(  65)			int count = 0;
HXLINE(  66)			{
HXLINE(  66)				int _g = 0;
HXDLIN(  66)				while((_g < items->length)){
HXLINE(  66)					 ::shoppingcart::ItemModel item = items->__get(_g).StaticCast<  ::shoppingcart::ItemModel >();
HXDLIN(  66)					_g = (_g + 1);
HXLINE(  67)					if (::hx::IsNotNull( item )) {
HXLINE(  68)						total = (total + (( (Float)(item->qty) ) * item->price));
HXLINE(  69)						count = (count + item->qty);
            					}
            				}
            			}
HXLINE(  72)			 ::Dynamic summary =  ::Dynamic(::hx::Anon_obj::Create(2)
            				->setFixed(0,HX_("items",00,ac,0c,c2),count)
            				->setFixed(1,HX_("total",c4,53,32,14),total));
HXLINE(  76)			callback(summary);
            		}
            		HX_END_LOCAL_FUNC1((void))

            	HX_STACKFRAME(&_hx_pos_b09c8a736b8e9c2d_63_GetCartSummary)
HXDLIN(  63)		this->itemRepo->FindByCartId(cartId, ::Dynamic(new _hx_Closure_0(callback)));
            	}


HX_DEFINE_DYNAMIC_FUNC2(ShoppingCartLogic_obj,GetCartSummary,(void))

void ShoppingCartLogic_obj::Clear(::String cartId, ::Dynamic callback){
            		HX_BEGIN_LOCAL_FUNC_S1(::hx::LocalFunc,_hx_Closure_0, ::Dynamic,callback) HXARGC(0)
            		void _hx_run(){
            			HX_STACKFRAME(&_hx_pos_b09c8a736b8e9c2d_81_Clear)
HXLINE(  81)			callback();
            		}
            		HX_END_LOCAL_FUNC0((void))

            	HX_STACKFRAME(&_hx_pos_b09c8a736b8e9c2d_80_Clear)
HXDLIN(  80)		this->cartRepo->Remove(cartId, ::Dynamic(new _hx_Closure_0(callback)));
            	}


HX_DEFINE_DYNAMIC_FUNC2(ShoppingCartLogic_obj,Clear,(void))


::hx::ObjectPtr< ShoppingCartLogic_obj > ShoppingCartLogic_obj::__new( ::shoppingcart::CartRepository cartRepo, ::shoppingcart::ItemRepository itemRepo) {
	::hx::ObjectPtr< ShoppingCartLogic_obj > __this = new ShoppingCartLogic_obj();
	__this->__construct(cartRepo,itemRepo);
	return __this;
}

::hx::ObjectPtr< ShoppingCartLogic_obj > ShoppingCartLogic_obj::__alloc(::hx::Ctx *_hx_ctx, ::shoppingcart::CartRepository cartRepo, ::shoppingcart::ItemRepository itemRepo) {
	ShoppingCartLogic_obj *__this = (ShoppingCartLogic_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(ShoppingCartLogic_obj), true, "shoppingcart.ShoppingCartLogic"));
	*(void **)__this = ShoppingCartLogic_obj::_hx_vtable;
	__this->__construct(cartRepo,itemRepo);
	return __this;
}

ShoppingCartLogic_obj::ShoppingCartLogic_obj()
{
}

void ShoppingCartLogic_obj::__Mark(HX_MARK_PARAMS)
{
	HX_MARK_BEGIN_CLASS(ShoppingCartLogic);
	HX_MARK_MEMBER_NAME(cartRepo,"cartRepo");
	HX_MARK_MEMBER_NAME(itemRepo,"itemRepo");
	HX_MARK_END_CLASS();
}

void ShoppingCartLogic_obj::__Visit(HX_VISIT_PARAMS)
{
	HX_VISIT_MEMBER_NAME(cartRepo,"cartRepo");
	HX_VISIT_MEMBER_NAME(itemRepo,"itemRepo");
}

::hx::Val ShoppingCartLogic_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 5:
		if (HX_FIELD_EQ(inName,"Clear") ) { return ::hx::Val( Clear_dyn() ); }
		break;
	case 6:
		if (HX_FIELD_EQ(inName,"Create") ) { return ::hx::Val( Create_dyn() ); }
		break;
	case 7:
		if (HX_FIELD_EQ(inName,"AddItem") ) { return ::hx::Val( AddItem_dyn() ); }
		break;
	case 8:
		if (HX_FIELD_EQ(inName,"cartRepo") ) { return ::hx::Val( cartRepo ); }
		if (HX_FIELD_EQ(inName,"itemRepo") ) { return ::hx::Val( itemRepo ); }
		break;
	case 9:
		if (HX_FIELD_EQ(inName,"ListItems") ) { return ::hx::Val( ListItems_dyn() ); }
		if (HX_FIELD_EQ(inName,"UpdateQty") ) { return ::hx::Val( UpdateQty_dyn() ); }
		break;
	case 10:
		if (HX_FIELD_EQ(inName,"RemoveItem") ) { return ::hx::Val( RemoveItem_dyn() ); }
		if (HX_FIELD_EQ(inName,"CountItems") ) { return ::hx::Val( CountItems_dyn() ); }
		break;
	case 14:
		if (HX_FIELD_EQ(inName,"GetCartSummary") ) { return ::hx::Val( GetCartSummary_dyn() ); }
	}
	return super::__Field(inName,inCallProp);
}

::hx::Val ShoppingCartLogic_obj::__SetField(const ::String &inName,const ::hx::Val &inValue,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 8:
		if (HX_FIELD_EQ(inName,"cartRepo") ) { cartRepo=inValue.Cast<  ::shoppingcart::CartRepository >(); return inValue; }
		if (HX_FIELD_EQ(inName,"itemRepo") ) { itemRepo=inValue.Cast<  ::shoppingcart::ItemRepository >(); return inValue; }
	}
	return super::__SetField(inName,inValue,inCallProp);
}

void ShoppingCartLogic_obj::__GetFields(Array< ::String> &outFields)
{
	outFields->push(HX_("cartRepo",72,12,cf,75));
	outFields->push(HX_("itemRepo",25,cf,a3,a8));
	super::__GetFields(outFields);
};

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo ShoppingCartLogic_obj_sMemberStorageInfo[] = {
	{::hx::fsObject /*  ::shoppingcart::CartRepository */ ,(int)offsetof(ShoppingCartLogic_obj,cartRepo),HX_("cartRepo",72,12,cf,75)},
	{::hx::fsObject /*  ::shoppingcart::ItemRepository */ ,(int)offsetof(ShoppingCartLogic_obj,itemRepo),HX_("itemRepo",25,cf,a3,a8)},
	{ ::hx::fsUnknown, 0, null()}
};
static ::hx::StaticInfo *ShoppingCartLogic_obj_sStaticStorageInfo = 0;
#endif

static ::String ShoppingCartLogic_obj_sMemberFields[] = {
	HX_("cartRepo",72,12,cf,75),
	HX_("itemRepo",25,cf,a3,a8),
	HX_("Create",1c,db,a3,b0),
	HX_("AddItem",b4,2f,4e,4f),
	HX_("ListItems",a2,4a,20,7a),
	HX_("RemoveItem",97,03,90,b9),
	HX_("UpdateQty",8d,e1,b5,24),
	HX_("CountItems",d1,0c,11,83),
	HX_("GetCartSummary",50,78,c5,0c),
	HX_("Clear",6d,e1,88,db),
	::String(null()) };

::hx::Class ShoppingCartLogic_obj::__mClass;

void ShoppingCartLogic_obj::__register()
{
	ShoppingCartLogic_obj _hx_dummy;
	ShoppingCartLogic_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("shoppingcart.ShoppingCartLogic",10,02,e2,07);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &::hx::Class_obj::GetNoStaticField;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(0 /* sStaticFields */);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(ShoppingCartLogic_obj_sMemberFields);
	__mClass->mCanCast = ::hx::TCanCast< ShoppingCartLogic_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = ShoppingCartLogic_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = ShoppingCartLogic_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace shoppingcart
