// Based on code Generated by Haxe 4.1.1
#include <hxcpp.h>

#ifndef INCLUDED_haxe_StackItem
#include <haxe/StackItem.h>
#endif
#ifndef INCLUDED_ValueType
#include <ValueType.h>
#endif
#ifndef INCLUDED_shoppingcart_ShoppingCart
#include <shoppingcart/ShoppingCart.h>
#endif
#ifndef INCLUDED_shoppingcart_ShoppingCartLogic
#include <shoppingcart/ShoppingCartLogic.h>
#endif
#ifndef INCLUDED_shoppingcart_ItemRepository
#include <shoppingcart/ItemRepository.h>
#endif
#ifndef INCLUDED_shoppingcart_ItemModel
#include <shoppingcart/ItemModel.h>
#endif
#ifndef INCLUDED_shoppingcart_CartRepository
#include <shoppingcart/CartRepository.h>
#endif
#ifndef INCLUDED_shoppingcart_CartModel
#include <shoppingcart/CartModel.h>
#endif
#ifndef INCLUDED_haxe_iterators_MapKeyValueIterator
#include <haxe/iterators/MapKeyValueIterator.h>
#endif
#ifndef INCLUDED_haxe_iterators_HashMapKeyValueIterator
#include <haxe/iterators/HashMapKeyValueIterator.h>
#endif
#ifndef INCLUDED_haxe_iterators_ArrayKeyValueIterator
#include <haxe/iterators/ArrayKeyValueIterator.h>
#endif
#ifndef INCLUDED_haxe_iterators_ArrayIterator
#include <haxe/iterators/ArrayIterator.h>
#endif
#ifndef INCLUDED_haxe_ds_WeakMap
#include <haxe/ds/WeakMap.h>
#endif
#ifndef INCLUDED_haxe_ds__Vector_Vector_Impl_
#include <haxe/ds/_Vector/Vector_Impl_.h>
#endif
#ifndef INCLUDED_haxe_ds_StringMap
#include <haxe/ds/StringMap.h>
#endif
#ifndef INCLUDED_haxe_ds_ObjectMap
#include <haxe/ds/ObjectMap.h>
#endif
#ifndef INCLUDED_haxe_ds__Map_Map_Impl_
#include <haxe/ds/_Map/Map_Impl_.h>
#endif
#ifndef INCLUDED_haxe_ds_IntMap
#include <haxe/ds/IntMap.h>
#endif
#ifndef INCLUDED_haxe_ds__HashMap_HashMapData
#include <haxe/ds/_HashMap/HashMapData.h>
#endif
#ifndef INCLUDED_haxe_ds__HashMap_HashMap_Impl_
#include <haxe/ds/_HashMap/HashMap_Impl_.h>
#endif
#ifndef INCLUDED_haxe_ds_EnumValueMap
#include <haxe/ds/EnumValueMap.h>
#endif
#ifndef INCLUDED_haxe_ds_TreeNode
#include <haxe/ds/TreeNode.h>
#endif
#ifndef INCLUDED_haxe_ds_BalancedTree
#include <haxe/ds/BalancedTree.h>
#endif
#ifndef INCLUDED_haxe_ValueException
#include <haxe/ValueException.h>
#endif
#ifndef INCLUDED_haxe_NativeStackTrace
#include <haxe/NativeStackTrace.h>
#endif
#ifndef INCLUDED_haxe_Exception
#include <haxe/Exception.h>
#endif
#ifndef INCLUDED_haxe_IMap
#include <haxe/IMap.h>
#endif
#ifndef INCLUDED_haxe__CallStack_CallStack_Impl_
#include <haxe/_CallStack/CallStack_Impl_.h>
#endif
#ifndef INCLUDED_Type
#include <Type.h>
#endif
#ifndef INCLUDED_StringBuf
#include <StringBuf.h>
#endif
#ifndef INCLUDED_Std
#include <Std.h>
#endif
#ifndef INCLUDED_Reflect
#include <Reflect.h>
#endif
#ifndef INCLUDED_IntIterator
#include <IntIterator.h>
#endif
#ifndef INCLUDED__EnumValue_EnumValue_Impl_
#include <_EnumValue/EnumValue_Impl_.h>
#endif


void __boot_shoppingcart()
{
//only boot once
static bool already_called = false;
if (already_called) return;
already_called = true;

::haxe::StackItem_obj::__register();
::ValueType_obj::__register();
::shoppingcart::ShoppingCart_obj::__register();
::shoppingcart::ShoppingCartLogic_obj::__register();
::shoppingcart::ItemRepository_obj::__register();
::shoppingcart::ItemModel_obj::__register();
::shoppingcart::CartRepository_obj::__register();
::shoppingcart::CartModel_obj::__register();
::haxe::iterators::MapKeyValueIterator_obj::__register();
::haxe::iterators::HashMapKeyValueIterator_obj::__register();
::haxe::iterators::ArrayKeyValueIterator_obj::__register();
::haxe::iterators::ArrayIterator_obj::__register();
::haxe::ds::WeakMap_obj::__register();
::haxe::ds::_Vector::Vector_Impl__obj::__register();
::haxe::ds::StringMap_obj::__register();
::haxe::ds::ObjectMap_obj::__register();
::haxe::ds::_Map::Map_Impl__obj::__register();
::haxe::ds::IntMap_obj::__register();
::haxe::ds::_HashMap::HashMapData_obj::__register();
::haxe::ds::_HashMap::HashMap_Impl__obj::__register();
::haxe::ds::EnumValueMap_obj::__register();
::haxe::ds::TreeNode_obj::__register();
::haxe::ds::BalancedTree_obj::__register();
::haxe::ValueException_obj::__register();
::haxe::NativeStackTrace_obj::__register();
::haxe::Exception_obj::__register();
::haxe::IMap_obj::__register();
::haxe::_CallStack::CallStack_Impl__obj::__register();
::Type_obj::__register();
::StringBuf_obj::__register();
::Std_obj::__register();
::Reflect_obj::__register();
::IntIterator_obj::__register();
::_EnumValue::EnumValue_Impl__obj::__register();
::haxe::StackItem_obj::__boot();
::ValueType_obj::__boot();
::shoppingcart::ShoppingCart_obj::__boot();
}

